### ISSUE TITLE
An advice about boot-args of config.plist

### ISSUE THREAD

**Issue by ske1996** [tmbt78/Huawei-Matebook-X-2020-Hackintosh#2]
Hi,
I am so happy to see you've done a remarkable job.My friend who has same laptop and we tested your build on his.
we found a problem(1 of 6 
on matebook x,we've got a group,lol) that is when you try to boot bigsur and the screen will be black about 3 mins,but even the screen is black,it still doing the boot processing and get into OS.
we found it is caused by whatevergreen and just add "-gfxblr" to boot-args will fix it.
since an update of WEG,it happened on my matebook 13's project,too.
i hope this experience could help someone who got that problem,even it is a low rate in our test.

Anyway,so happy to see you make it so perfectly.

Bless you,

Kitsu.

**Comment by tmbt78** [comment]
Thanks,
that's strange because i'm using enable-backlight-registers-fix property which it's the same than that boot-args ..
Are you using my last EFI ?

Also there is a great news! Few moments ago i was able to fix the touchpad and now it works in interrupt mode !!
I will update the EFI in the weekend.

Mattia

**Comment by ske1996** [comment]
> Thanks,
> 
> that's strange because i'm using enable-backlight-registers-fix property which it's the same than that boot-args ..
> 
> Are you using my last EFI ?
> 
> 
> 
> Also there is a great news! Few moments ago i was able to fix the touchpad and now it works in interrupt mode !!
> 
> I will update the EFI in the weekend.
> 
> 
> 
> Mattia
> 
> 

Yes,i agree with you.it should be same on paper.but if i didnt see it happened,i wouldnt believe it,too.and it dosent happened every time and not every device.and that happened at another laptop in same case.so...even that two method are same on paper,maybe there are some difference in hardware-lvl.

And congratulations！！that is  so impressive！！i cant wait it🤩🤩🤩I think i can learn lots of things from that.

btw,may it wont happen,but i have some experience in matebook 13/14 2020 want to share with you,it has a touchable screen,too.trackpad and touch screen both work until we use them at sametime.then they dont work like never do.so i serched alot and find a method that you have to rename screen device in acpi(if use gpio interrupt mode),otherwise it will casue that issue.(but we chosed to ban touchscreen device in acpi at last)

**Comment by tmbt78** [comment]
@ske1996 I've updated the EFI with the new touchpad SSDT and added the boot-args as suggested.
